sudo: required
language: java
jdk: openjdk13

services:
 - docker

#before_install:
# - docker build -t lilachyonash/react-test -f ./client/Dockerfile.dev ./client
 
#script:
# - ./mvnw clean install -B

after_success:
   - docker build -t lilachyonash/docker-k8s-hello-world .
   - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
   - docker push lilachyonash/docker-k8s-hello-world .