sudo: required
language: java
jdk: openjdk13

services:
 - docker

#before_install:
# - docker build -t lilachyonash/react-test -f ./client/Dockerfile.dev ./client
 
install:
 - mvn -N io.takari:maven:wrapper
 - ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

after_success:
   - docker build -t lilachaimo/docker-k8s-hello-world .
   - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
   - docker tag lilachyonash/docker-k8s-hello-world:7 lilachyonash/docker-k8s-hello-world:latest
   - docker push lilachyonash/docker-k8s-hello-world .